"""Tests for terrastep.skilldoc: the generator, and `skill install` across both
an editable and a regular (non-editable) install of the package (B3)."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from terrastep import skilldoc

REPO = Path(__file__).resolve().parent.parent


def test_render_all_produces_the_five_expected_files():
    rendered = skilldoc.render_all()
    assert set(rendered) == {
        "journal/terrastep_101.md", "skill/SKILL.md",
        "skill/references/format.md", "skill/references/verbs.md",
        "skill/references/brain_budget.md",
    }
    for text in rendered.values():
        assert "GENERATED by `terrastep skill build`" in text


def test_skill_md_has_a_name_and_description_frontmatter():
    text = skilldoc.render_skill_md()
    assert text.startswith("---\nname: terrastep\n")
    assert "description:" in text.splitlines()[2]


def test_failure_code_table_lists_every_registered_code():
    from terrastep import core
    table = skilldoc._failure_code_table()
    for code in core.FAILURE_CODES:
        assert f"`{code}`" in table


def test_checked_in_generated_files_are_not_stale():
    """Mirrors core.py's stale-index check, applied to the generated docs themselves (B4):
    if this fails, someone changed a rule in core.py/config.py/cli.py without running
    `terrastep skill build`."""
    rendered = skilldoc.render_all()
    pkg_dir = Path(skilldoc.__file__).resolve().parent
    for rel, expected in rendered.items():
        path = (pkg_dir if rel.startswith("skill/") else REPO) / rel
        assert path.exists(), f"{rel} does not exist; run `terrastep skill build`"
        assert path.read_text(encoding="utf-8") == expected, (
            f"{rel} is stale relative to the generator; run `terrastep skill build`")


def test_skill_install_refuses_to_overwrite_without_force(tmp_path):
    from terrastep import cli
    (tmp_path / ".claude" / "skills" / "terrastep").mkdir(parents=True)
    assert cli.main(["skill", "install", "--root", str(tmp_path)]) == 1
    assert cli.main(["skill", "install", "--root", str(tmp_path), "--force"]) == 0
    assert (tmp_path / ".claude" / "skills" / "terrastep" / "SKILL.md").exists()


def test_skill_install_works_from_a_regular_non_editable_install(tmp_path):
    """B3: locate bundled package data the same way whether the install is editable
    (src/terrastep/skill/...) or regular (site-packages/terrastep/skill/...)."""
    target_dir = tmp_path / "regular_install"
    r = subprocess.run([sys.executable, "-m", "pip", "install", "--no-deps",
                        "--target", str(target_dir), str(REPO)],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    assert (target_dir / "terrastep" / "skill" / "SKILL.md").exists()

    install_root = tmp_path / "consumer_repo"
    install_root.mkdir()
    env = {"PYTHONPATH": str(target_dir), "PATH": "/usr/bin:/bin"}
    r = subprocess.run([sys.executable, "-m", "terrastep", "skill", "install", "--root", str(install_root)],
                       capture_output=True, text=True, env=env)
    assert r.returncode == 0, r.stderr
    assert (install_root / ".claude" / "skills" / "terrastep" / "SKILL.md").exists()
    # Confirm it came from the regular install's files, not this test process's editable one.
    installed_text = (install_root / ".claude" / "skills" / "terrastep" / "SKILL.md").read_text()
    bundled_text = (target_dir / "terrastep" / "skill" / "SKILL.md").read_text()
    assert installed_text == bundled_text


def test_every_config_help_key_appears_in_the_generated_config_table():
    from terrastep.config import CONFIG_HELP
    table = skilldoc._config_table()
    for key, text in CONFIG_HELP.items():
        assert text in table, f"CONFIG_HELP[{key!r}] is missing from the generated table"
