"""Generates journal/terrastep_101.md and the bundled Claude Code skill from
this package's own constants (core.py, config.py, cli.py) — one source of
truth, not hand-written prose that can drift from the rules it describes.

  terrastep skill build     regenerates the checked-in copies (maintainer use)
  terrastep skill install   copies the bundled, already-generated skill into
                             another repo's .claude/skills/ (end-user use)

This module only renders text. It never decides where the result is written;
callers (cli.py) do that.
"""

from __future__ import annotations

import argparse
import json

from . import __version__, budget, core
from .cli import build_parser
from .config import CONFIG_HELP, Config

GENERATED_NOTE = "GENERATED by `terrastep skill build` from terrastep's own code. Do not edit by hand."


def _header(title: str) -> str:
    return f"<!-- {GENERATED_NOTE} (terrastep {__version__}) -->\n\n# {title}\n"


def _verb_help() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """[(verb, help text, [(flag, help text), ...]), ...], read from cli.py's own argparse
    setup. A verb built with nested subparsers (0005: `plan`) is expanded into one row per
    action, named "verb action" (e.g. "plan precheck"), each with its own flags."""
    parser = build_parser()
    subparsers_action = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    out = []
    for choice_action in subparsers_action._choices_actions:
        name = choice_action.dest
        sub = subparsers_action.choices[name]
        nested = next((a for a in sub._actions if isinstance(a, argparse._SubParsersAction)), None)
        if nested is None:
            flags = [(a.option_strings[0], a.help) for a in sub._actions
                     if a.option_strings and a.help]
            out.append((name, choice_action.help, flags))
            continue
        for nested_choice in nested._choices_actions:
            nested_name = nested_choice.dest
            nested_sub = nested.choices[nested_name]
            flags = [(a.option_strings[0], a.help) for a in nested_sub._actions
                     if a.option_strings and a.help]
            out.append((f"{name} {nested_name}", nested_choice.help, flags))
    return out


def _failure_code_table() -> str:
    rows = [f"| `{code}` | {msg} |" for code, msg in core.FAILURE_CODES.items()]
    return "| Code | Meaning |\n|---|---|\n" + "\n".join(rows)


def _verb_table() -> str:
    rows = []
    for name, help_text, flags in _verb_help():
        flag_text = "; ".join(f"`{f}`: {h}" for f, h in flags)
        rows.append(f"| `terrastep {name}` | {help_text} | {flag_text} |")
    return "| Verb | Does | Flags |\n|---|---|---|\n" + "\n".join(rows)


def _brain_budget_config_rows() -> list[str]:
    """Just the [brain_budget]/[brain_budget.limits] rows — shared by the full
    config table (terrastep_101.md, verbs.md) and the brain budget reference
    (0006), which shows only these."""
    bb = Config().brain_budget
    return [
        f"| `[brain_budget] enabled` | `{bb.enabled!r}` | {CONFIG_HELP['brain_budget.enabled']} |",
        f"| `[brain_budget] max_retries` | `{bb.max_retries!r}` | "
        f"{CONFIG_HELP['brain_budget.max_retries']} |",
        f"| `[brain_budget.limits] evaluative_count` | `{bb.limits.evaluative_count!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.evaluative_count']} |",
        f"| `[brain_budget.limits] dependency_edge_count` | "
        f"`{bb.limits.dependency_edge_count!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.dependency_edge_count']} |",
        f"| `[brain_budget.limits] largest_coupled_cluster_size` | "
        f"`{bb.limits.largest_coupled_cluster_size!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.largest_coupled_cluster_size']} |",
        f"| `[brain_budget.limits] word_count` | `{bb.limits.word_count!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.word_count']} |",
    ]


def _config_table() -> str:
    default = Config()
    rows = [
        f"| `scan_dirs` | `{list(default.scan_dirs)!r}` | {CONFIG_HELP['scan_dirs']} |",
        f"| `index_file` | `{default.index_file!r}` | {CONFIG_HELP['index_file']} |",
        f"| `exclude` | `{list(default.exclude)!r}` | {CONFIG_HELP['exclude']} |",
        f"| `id_floor` | `{default.id_floor!r}` | {CONFIG_HELP['id_floor']} |",
        f"| `in_progress_cap` | `{default.in_progress_cap!r}` | {CONFIG_HELP['in_progress_cap']} |",
        f"| `[aliases]` | (none) | {CONFIG_HELP['aliases']} |",
        f"| `warn_bare_section` | `{default.warn_bare_section!r}` | {CONFIG_HELP['warn_bare_section']} |",
        f"| `[migrate] changelog` | (none) | {CONFIG_HELP['migrate.changelog']} |",
        f"| `[migrate] legacy_dir` | (none) | {CONFIG_HELP['migrate.legacy_dir']} |",
        *_brain_budget_config_rows(),
    ]
    return "| Key | Default | Meaning |\n|---|---|---|\n" + "\n".join(rows)


def _measures_table() -> str:
    limits = Config().brain_budget.limits
    rows = budget.FORMAT_DEFINITION["complexity"]["rows"]
    lines = ["| Measure | Label | Default limit |", "|---|---|---:|"]
    lines += [f"| `{machine}` | {label} | {getattr(limits, machine)} |" for machine, label in rows]
    return "\n".join(lines)


def _brain_budget_code_table() -> str:
    rows = [f"| `{code}` | {msg} |" for code, msg in core.FAILURE_CODES.items()
            if code.startswith("brain-budget-")]
    return "| Code | Meaning |\n|---|---|\n" + "\n".join(rows)


def _states_and_types_table() -> str:
    return (
        "| | |\n|---|---|\n"
        f"| `status` | one of {list(core.STATES)} |\n"
        f"| A `note`'s `status` | one of {list(core.NOTE_STATES)} |\n"
        f"| `type` | one of {list(core.TYPES)} (`{core.PLAN_TYPES[0]}` is the only type "
        f"checked against the body shape below) |\n"
        f"| `closed_reason`, when `status: closed` | one of {list(core.CLOSED_REASONS)} |"
    )


def _role_alias_table() -> str:
    rows = [f"| `{role}` | {', '.join(f'`{p}`' for p in patterns)} |"
            for role, patterns in core.ROLE_ALIASES.items()]
    return "| Role | Heading patterns (prefix match) |\n|---|---|\n" + "\n".join(rows)


TERRASTEP_101_HOW_TO_USE = """\
## 4. How to use them

**Starting a new proposal:**

```
terrastep next-id                         # → 0002
# write journal/plans/v0.1/0002_my_proposal.md, type: plan, status: planning
terrastep check                           # confirm it passes
terrastep build                           # regenerate the index
```

**Day to day:** `terrastep install-hooks` once per clone; after that, the pre-commit hook and (in
a Claude Code session) the Stop hook keep the index and every document's frontmatter honest
without you thinking about it. Run `terrastep check` by hand any time to see the full picture, and
`terrastep build` after editing any document's `status`.

**Bringing an existing pile of undocumented markdown under the format:**

```
terrastep migrate propose     # writes a proposal table under scan_dirs[0]; touches nothing else
# review the table by hand — it's only a guess, and flags weak ones
terrastep migrate apply       # prepends the reviewed frontmatter; refuses any doc that already has some
terrastep build && terrastep check
```

**Bringing a new repository under the format for the first time:** write a `terrastep.toml` naming
`scan_dirs`, run `terrastep migrate propose`/`apply` on what's there already, then
`terrastep install-hooks`. To also make terrastep available to Claude Code in that repo, run
`terrastep skill install`.
"""


def render_terrastep_101() -> str:
    parts = [
        _header("terrastep 101"),
        "A plain explainer, not a proposal: it carries no frontmatter on purpose, because it does "
        "not sit in a designated `scan_dirs` directory. See \"1. The format\" below for what that "
        "means.\n",
        "## 1. The format\n",
        "terrastep is a frontmatter-and-body convention for planning documents (plan docs, "
        "proposals, notes), plus a CLI that checks a repository against it. It does not apply to "
        "every markdown file in a repository — only to files inside directories you name in "
        "`terrastep.toml`. Everything else is ordinary markdown, free to look however you like.\n",
        "### States, types, and closed reasons\n",
        _states_and_types_table(),
        "\n### Role headings (front sections, before the decision sections)\n",
        _role_alias_table(),
        "\n### The body, for `type: plan`\n",
        "Only `plan` documents get the body-shape check (`legacy` and `note` are exempt): at "
        "least one non-empty `summary` or `motivation` section, then exactly `## Blockers`, "
        "`## Questions`, `## Recommendations`, `## Sequencing` in that order and nothing else "
        "between them. Blockers/Questions hold items (`B1`, `Q1`, ...); every blocker needs "
        "exactly one `[open]`/`[resolved]` tag; every item needs a recommendation "
        "(`**Recommendation...` or `→ **answer**`); Recommendations must mention every still-open "
        "item by id. Anything after Sequencing needs a `YYYY-MM-DD` in its heading. "
        "`status: ready`/`in-progress` fails if a blocker is still `[open]`; "
        "`status: implemented` needs a `history`-role section.\n",
        "### Failure codes\n",
        _failure_code_table(),
        "\n## 2. The tools\n",
        "One installed command, `terrastep`:\n",
        _verb_table(),
        "\nEvery verb takes `--root DIR` and `--config FILE`; both default to auto-detection "
        "(nearest parent holding `terrastep.toml`, then the git root, then the current "
        "directory).\n",
        "### Config: `terrastep.toml`\n",
        _config_table(),
        "\n`scan_dirs` is the one setting that matters most: only files under a listed directory "
        "(recursively) are ever touched by `check`, `build`, or the hooks.\n",
        "### Hooks\n",
        "- **Pre-commit** (`terrastep install-hooks`): blocks a commit whose staged `scan_dirs` "
        "snapshot fails `terrastep check`. `git commit --no-verify` bypasses it.\n"
        "- **Claude Code Stop hook** (`integrations/claude/stop_hook.sh`): before a session ends, "
        "runs `terrastep check --if-changed` and blocks the stop if it fails. Silent when nothing "
        "under `scan_dirs` changed.\n",
        "\n## 3. Brain budget\n",
        "An optional layer on `type: plan` documents, off by default. `[brain_budget] enabled "
        "= true` in `terrastep.toml` turns it on: it measures how much judgment a plan's "
        "reviewer must give at once, shows the result in a `## Complexity` section terrastep "
        "writes, and never fails a document for being over its limits — only for a malformed "
        "ledger. `terrastep plan budget|precheck|render|scaffold` and the fields "
        "`terrastep check --format json` adds are in \"2. The tools\" above; the full ledger "
        "schema and edge rules are in the bundled skill's `references/brain_budget.md`.\n",
        _measures_table(),
        "",
        TERRASTEP_101_HOW_TO_USE,
    ]
    return "\n".join(parts) + "\n"


SKILL_PROCEDURE = """\
## First: does terrastep even apply here?

Before treating any rule below as binding, check that it applies to the file you're about to
write or edit:

1. Does this repository have a `terrastep.toml` at its root (or does `terrastep` run without
   error, meaning it found one, or is running on defaults)?
2. Is the file under one of `scan_dirs` (recursively)? Run `terrastep survey` or read
   `terrastep.toml`'s `scan_dirs` if unsure.

If either answer is no, the format does not apply to this file — write it however the task needs,
and stop reading here. This skill only governs documents that terrastep itself would scan.

## Writing a new `type: plan` document

1. `terrastep next-id` for the number.
2. Scaffold: `terrastep plan scaffold --title "..."` (works whether brain budget is on or off).
   Never write the frontmatter or the file by hand. See `references/format.md` for the full body
   shape (item tags, recommendation coverage, role headings).
3. `terrastep check`. On any failure, look up the code in `references/format.md` and fix it —
   don't guess twice at the same rule.
4. `terrastep build` to regenerate the index.
5. Re-run `terrastep check` before finishing the turn. Closing this loop here is what makes the
   pre-commit and Stop hooks (already installed if this repo ran `terrastep install-hooks`)
   uneventful rather than a surprise later.

## Writing plan documents under a brain budget

Use this procedure when you are asked to plan or design work and `terrastep plan budget`
reports `"enabled": true`. When it reports `false`, follow the procedure above without the
budget steps.

1. **Read the budget.** Run `terrastep plan budget --format json`. Use its limits and
   `max_retries`. Do not assume the defaults. Do not copy the limits into any file.
2. **Decompose before writing.** List every evaluation element: each consequential choice
   (another plausible answer would change behavior, a public contract, persistent state, access
   control, or the implementation approach; a recommended default still counts) and each
   assumption the reviewer must judge. An evaluation element that must be settled or verified
   before work starts is a blocker; any other is a question. For each pair of evaluation
   elements, ask: "If the first answer changed, would I have to reconsider the second? What
   specific constraint would change?" Keep coupled evaluation elements in one plan. Split
   plans only where one plan can rely on a stated contract from another. There is no limit
   on the number of plans.
3. **Order the plans** so each comes after its prerequisites. A prerequisite must pass
   `terrastep check` before you scaffold a plan that depends on it.
4. **Scaffold** each plan with `terrastep plan scaffold`. Never create or overwrite a plan
   file by hand.
5. **Declare.** Read each prerequisite's file for its contract. Write the evaluation elements in
   Blockers and Questions, each with a recommendation. In `brain_budget`, add the edges and a
   `contract` for each `depends_on` entry. Use `sequencing` (supplier to consumer) only when the
   supplying answer can stay fixed. Use `coupled` when the evaluation elements must be judged
   together, or when you are unsure. One record per pair, direct constraints only. Never write
   `schema_version`, `policy_id`, or the Complexity box.
6. **Precheck** with `terrastep plan precheck FILE --format json` before you write prose. Fix
   what it reports. If a measure is over budget and an honest re-split exists, try it. If the
   excess is a coupled cluster, keep it together; the plan will be flagged.
7. **Write the prose.** Replace every draft marker. Recommendations must mention every open
   evaluation element. If writing reveals a new choice, assumption or dependency, make it an
   evaluation element or an edge and precheck again.
8. **Render and check.** Run `terrastep plan render FILE`, then
   `terrastep check FILE --format json`. Patch only what the diagnostics name. Render again if a
   patch changes a measure. Check again after the last edit.
9. **Respect `max_retries`.** A retry is one round of changes after a reported failure or an
   over-budget measure. The count is per plan, shared between precheck and check. When it runs
   out, deliver the plan: flagged if it is over budget, or as a failed draft if format
   failures remain.
10. **Finish.** Run `terrastep build`, then `terrastep check`. Report each plan in
    prerequisite order, with whether it is within budget, which measure is over and what split
    you tried, and its open blockers. Never claim a check that did not run.

Never make a plan look within budget by deleting a real evaluation element, merging
independent evaluation elements, leaving a choice in prose, relabeling a coupled edge as
sequencing, or splitting coupled evaluation elements across plans.

## Fixing a document that fails `terrastep check`

Read the failure code from the output, find it in `references/format.md`, apply the fix, re-run
`terrastep check`. Never guess at a fix without reading what the code actually means — the codes
are specific (e.g. `body-r-cover` means a Recommendations section is missing an item's id, not
that recommendations are missing entirely).

## Bringing existing undocumented markdown under the format

```
terrastep migrate propose     # writes a proposal table; touches nothing else
# review the table by hand — it is only a guess, and flags weak ones
terrastep migrate apply       # prepends the reviewed frontmatter
terrastep build && terrastep check
```

## Setting terrastep up in a repository for the first time

Write a `terrastep.toml` naming `scan_dirs`, run `migrate propose`/`apply` on what's already
there, then `terrastep install-hooks`. See `references/verbs.md` for every verb and flag.
"""


def render_skill_md() -> str:
    frontmatter = (
        "---\n"
        "name: terrastep\n"
        "description: Use when writing, reviewing, or checking a terrastep plan document, "
        "when asked to plan or design work in a repository with a terrastep.toml, or when a "
        "task mentions terrastep, scan_dirs, brain budget, or the "
        "Blockers/Questions/Recommendations/Sequencing shape.\n"
        f"terrastep_version: {__version__}\n"
        "---\n"
    )
    body = (
        f"\n{GENERATED_NOTE} (terrastep {__version__})\n\n"
        "# terrastep\n\n"
        "terrastep checks planning documents against a frontmatter-and-body format. Full spec: "
        "`references/format.md`. Full verb/config reference: `references/verbs.md`. The optional "
        "brain budget layer: `references/brain_budget.md`.\n\n"
        + SKILL_PROCEDURE
    )
    return frontmatter + body


def render_reference_format() -> str:
    parts = [
        _header("terrastep format reference"),
        "### States, types, and closed reasons\n",
        _states_and_types_table(),
        "\n### Role headings\n",
        _role_alias_table(),
        "\n### Failure codes\n",
        _failure_code_table(),
    ]
    return "\n".join(parts) + "\n"


def render_reference_verbs() -> str:
    parts = [
        _header("terrastep verb and config reference"),
        "### Verbs\n",
        _verb_table(),
        "\n### `terrastep.toml`\n",
        _config_table(),
    ]
    return "\n".join(parts) + "\n"


BRAIN_BUDGET_EDGE_RULES = """\
An edge is a direct constraint between two evaluation elements in the same plan: the answer to
one changes the possible answers, required behavior, or acceptance criteria of the other. Two
elements about the same topic do not need an edge for that reason alone.

For each pair, ask: "If the answer to the first changed, would I have to reconsider the answer to
the second? What specific constraint would change?" If yes, declare an edge and write the
constraint in `contract`. If no, declare nothing.

- **`sequencing`**: one element supplies a contract that the other uses without reopening the
  supplier. `from` is the supplier, `to` is the consumer.
- **`coupled`**: the elements must be judged together because their tradeoffs or validity
  constrain each other. If it is uncertain whether they can be judged separately, use `coupled`.
- Declare direct constraints only. If Q1 constrains Q2 and Q2 constrains Q3, do not add Q1 → Q3
  just because that path exists.
- One record per pair. A `coupled` relationship replaces a `sequencing` record for the same pair.

A prerequisite (`depends_on`) means this plan cannot deliver its behavior until another plan
supplies a specific interface, invariant or capability — not that the other plan merely comes
earlier or covers a related feature. If this plan's choices could invalidate the other plan's
contract, the elements are coupled, not sequenced: put them in one plan instead.
"""


def render_reference_brain_budget() -> str:
    parts = [
        _header("brain budget reference"),
        "An optional layer on `type: plan` documents, off by default "
        "(`[brain_budget] enabled = false`). See `SKILL.md`'s \"Writing plan documents under a "
        "brain budget\" for the procedure, and `references/verbs.md` for every `terrastep plan` "
        "verb.\n",
        "### The four measures\n",
        _measures_table(),
        "\n### The ledger schema (JSON Schema 2020-12, this package's version)\n",
        "```json\n" + json.dumps(budget.working_schema(), indent=2) + "\n```\n",
        "### Declaring edges and prerequisites\n",
        BRAIN_BUDGET_EDGE_RULES,
        "### Failure codes\n",
        _brain_budget_code_table(),
        "\n### Configuration\n",
        "| Key | Default | Meaning |\n|---|---|---|\n" + "\n".join(_brain_budget_config_rows()),
    ]
    return "\n".join(parts) + "\n"


def render_all() -> dict[str, str]:
    """{relative path: content} for every generated file, terrastep_101.md and the skill."""
    return {
        "journal/terrastep_101.md": render_terrastep_101(),
        "skill/SKILL.md": render_skill_md(),
        "skill/references/format.md": render_reference_format(),
        "skill/references/verbs.md": render_reference_verbs(),
        "skill/references/brain_budget.md": render_reference_brain_budget(),
    }
