"""Generates journal/terrastep_101.md and the bundled Claude Code skill from
this package's own constants (core.py, config.py, cli.py) — one source of
truth, not hand-written prose that can drift from the rules it describes.

  terrastep skill build     regenerates the checked-in copies (maintainer use)
  terrastep skill install   copies the bundled, already-generated skill into
                             another repo's .claude/skills/ (end-user use)

This module only renders text. It never decides where the result is written;
callers (cli.py) do that.
"""

from __future__ import annotations

import argparse

from . import __version__, core
from .cli import build_parser
from .config import CONFIG_HELP, Config

GENERATED_NOTE = "GENERATED by `terrastep skill build` from terrastep's own code. Do not edit by hand."


def _header(title: str) -> str:
    return f"<!-- {GENERATED_NOTE} (terrastep {__version__}) -->\n\n# {title}\n"


def _verb_help() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """[(verb, help text, [(flag, help text), ...]), ...], read from cli.py's own argparse setup."""
    parser = build_parser()
    subparsers_action = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    out = []
    for choice_action in subparsers_action._choices_actions:
        name = choice_action.dest
        sub = subparsers_action.choices[name]
        flags = [(a.option_strings[0], a.help) for a in sub._actions
                 if a.option_strings and a.help]
        out.append((name, choice_action.help, flags))
    return out


def _failure_code_table() -> str:
    rows = [f"| `{code}` | {msg} |" for code, msg in core.FAILURE_CODES.items()]
    return "| Code | Meaning |\n|---|---|\n" + "\n".join(rows)


def _verb_table() -> str:
    rows = []
    for name, help_text, flags in _verb_help():
        flag_text = "; ".join(f"`{f}`: {h}" for f, h in flags)
        rows.append(f"| `terrastep {name}` | {help_text} | {flag_text} |")
    return "| Verb | Does | Flags |\n|---|---|---|\n" + "\n".join(rows)


def _config_table() -> str:
    default = Config()
    rows = [
        f"| `scan_dirs` | `{list(default.scan_dirs)!r}` | {CONFIG_HELP['scan_dirs']} |",
        f"| `index_file` | `{default.index_file!r}` | {CONFIG_HELP['index_file']} |",
        f"| `exclude` | `{list(default.exclude)!r}` | {CONFIG_HELP['exclude']} |",
        f"| `id_floor` | `{default.id_floor!r}` | {CONFIG_HELP['id_floor']} |",
        f"| `in_progress_cap` | `{default.in_progress_cap!r}` | {CONFIG_HELP['in_progress_cap']} |",
        f"| `[aliases]` | (none) | {CONFIG_HELP['aliases']} |",
        f"| `warn_bare_section` | `{default.warn_bare_section!r}` | {CONFIG_HELP['warn_bare_section']} |",
        f"| `[migrate] changelog` | (none) | {CONFIG_HELP['migrate.changelog']} |",
        f"| `[migrate] plan_dir` | (none) | {CONFIG_HELP['migrate.plan_dir']} |",
        f"| `[brain_budget] enabled` | `{default.brain_budget.enabled!r}` | "
        f"{CONFIG_HELP['brain_budget.enabled']} |",
        f"| `[brain_budget] max_retries` | `{default.brain_budget.max_retries!r}` | "
        f"{CONFIG_HELP['brain_budget.max_retries']} |",
        f"| `[brain_budget.limits] evaluative_count` | "
        f"`{default.brain_budget.limits.evaluative_count!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.evaluative_count']} |",
        f"| `[brain_budget.limits] dependency_edge_count` | "
        f"`{default.brain_budget.limits.dependency_edge_count!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.dependency_edge_count']} |",
        f"| `[brain_budget.limits] largest_coupled_cluster_size` | "
        f"`{default.brain_budget.limits.largest_coupled_cluster_size!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.largest_coupled_cluster_size']} |",
        f"| `[brain_budget.limits] word_count` | `{default.brain_budget.limits.word_count!r}` | "
        f"{CONFIG_HELP['brain_budget.limits.word_count']} |",
    ]
    return "| Key | Default | Meaning |\n|---|---|---|\n" + "\n".join(rows)


def _states_and_types_table() -> str:
    return (
        "| | |\n|---|---|\n"
        f"| `status` | one of {list(core.STATES)} |\n"
        f"| A `note`'s `status` | one of {list(core.NOTE_STATES)} |\n"
        f"| `type` | one of {list(core.TYPES)} (`{core.PLAN_TYPES[0]}` is the only type "
        f"checked against the body shape below) |\n"
        f"| `closed_reason`, when `status: closed` | one of {list(core.CLOSED_REASONS)} |"
    )


def _role_alias_table() -> str:
    rows = [f"| `{role}` | {', '.join(f'`{p}`' for p in patterns)} |"
            for role, patterns in core.ROLE_ALIASES.items()]
    return "| Role | Heading patterns (prefix match) |\n|---|---|\n" + "\n".join(rows)


TERRASTEP_101_HOW_TO_USE = """\
## 3. How to use them

**Starting a new proposal:**

```
terrastep next-id                         # → 0002
# write journal/plans/v0.1/0002_my_proposal.md, type: design, status: planning
terrastep check                           # confirm it passes
terrastep build                           # regenerate the index
```

**Day to day:** `terrastep install-hooks` once per clone; after that, the pre-commit hook and (in
a Claude Code session) the Stop hook keep the index and every document's frontmatter honest
without you thinking about it. Run `terrastep check` by hand any time to see the full picture, and
`terrastep build` after editing any document's `status`.

**Bringing an existing pile of undocumented markdown under the format:**

```
terrastep migrate propose     # writes a proposal table under scan_dirs[0]; touches nothing else
# review the table by hand — it's only a guess, and flags weak ones
terrastep migrate apply       # prepends the reviewed frontmatter; refuses any doc that already has some
terrastep build && terrastep check
```

**Bringing a new repository under the format for the first time:** write a `terrastep.toml` naming
`scan_dirs`, run `terrastep migrate propose`/`apply` on what's there already, then
`terrastep install-hooks`. To also make terrastep available to Claude Code in that repo, run
`terrastep skill install`.
"""


def render_terrastep_101() -> str:
    parts = [
        _header("terrastep 101"),
        "A plain explainer, not a proposal: it carries no frontmatter on purpose, because it does "
        "not sit in a designated `scan_dirs` directory. See \"1. The format\" below for what that "
        "means.\n",
        "## 1. The format\n",
        "terrastep is a frontmatter-and-body convention for planning documents (design docs, "
        "proposals, notes), plus a CLI that checks a repository against it. It does not apply to "
        "every markdown file in a repository — only to files inside directories you name in "
        "`terrastep.toml`. Everything else is ordinary markdown, free to look however you like.\n",
        "### States, types, and closed reasons\n",
        _states_and_types_table(),
        "\n### Role headings (front sections, before the decision sections)\n",
        _role_alias_table(),
        "\n### The body, for `type: design`\n",
        "Only `design` documents get the body-shape check (`legacy` and `note` are exempt): at "
        "least one non-empty `summary` or `motivation` section, then exactly `## Blockers`, "
        "`## Questions`, `## Recommendations`, `## Sequencing` in that order and nothing else "
        "between them. Blockers/Questions hold items (`B1`, `Q1`, ...); every blocker needs "
        "exactly one `[open]`/`[resolved]` tag; every item needs a recommendation "
        "(`**Recommendation...` or `→ **answer**`); Recommendations must mention every still-open "
        "item by id. Anything after Sequencing needs a `YYYY-MM-DD` in its heading. "
        "`status: ready`/`in-progress` fails if a blocker is still `[open]`; "
        "`status: implemented` needs a `history`-role section.\n",
        "### Failure codes\n",
        _failure_code_table(),
        "\n## 2. The tools\n",
        "One installed command, `terrastep`:\n",
        _verb_table(),
        "\nEvery verb takes `--root DIR` and `--config FILE`; both default to auto-detection "
        "(nearest parent holding `terrastep.toml`, then the git root, then the current "
        "directory).\n",
        "### Config: `terrastep.toml`\n",
        _config_table(),
        "\n`scan_dirs` is the one setting that matters most: only files under a listed directory "
        "(recursively) are ever touched by `check`, `build`, or the hooks.\n",
        "### Hooks\n",
        "- **Pre-commit** (`terrastep install-hooks`): blocks a commit whose staged `scan_dirs` "
        "snapshot fails `terrastep check`. `git commit --no-verify` bypasses it.\n"
        "- **Claude Code Stop hook** (`integrations/claude/stop_hook.sh`): before a session ends, "
        "runs `terrastep check --if-changed` and blocks the stop if it fails. Silent when nothing "
        "under `scan_dirs` changed.\n",
        TERRASTEP_101_HOW_TO_USE,
    ]
    return "\n".join(parts) + "\n"


SKILL_PROCEDURE = """\
## First: does terrastep even apply here?

Before treating any rule below as binding, check that it applies to the file you're about to
write or edit:

1. Does this repository have a `terrastep.toml` at its root (or does `terrastep` run without
   error, meaning it found one, or is running on defaults)?
2. Is the file under one of `scan_dirs` (recursively)? Run `terrastep survey` or read
   `terrastep.toml`'s `scan_dirs` if unsure.

If either answer is no, the format does not apply to this file — write it however the task needs,
and stop reading here. This skill only governs documents that terrastep itself would scan.

## Writing a new `type: design` document

1. `terrastep next-id` for the number.
2. Scaffold: frontmatter (`status: planning`, today's `status_changed`, `type: design`, `next`),
   at least a `summary` or `motivation` section, then exactly `## Blockers`, `## Questions`,
   `## Recommendations`, `## Sequencing` in that order. See `references/format.md` for the full
   shape (item tags, recommendation coverage, role headings).
3. `terrastep check`. On any failure, look up the code in `references/format.md` and fix it —
   don't guess twice at the same rule.
4. `terrastep build` to regenerate the index.
5. Re-run `terrastep check` before finishing the turn. Closing this loop here is what makes the
   pre-commit and Stop hooks (already installed if this repo ran `terrastep install-hooks`)
   uneventful rather than a surprise later.

## Fixing a document that fails `terrastep check`

Read the failure code from the output, find it in `references/format.md`, apply the fix, re-run
`terrastep check`. Never guess at a fix without reading what the code actually means — the codes
are specific (e.g. `body-r-cover` means a Recommendations section is missing an item's id, not
that recommendations are missing entirely).

## Bringing existing undocumented markdown under the format

```
terrastep migrate propose     # writes a proposal table; touches nothing else
# review the table by hand — it is only a guess, and flags weak ones
terrastep migrate apply       # prepends the reviewed frontmatter
terrastep build && terrastep check
```

## Setting terrastep up in a repository for the first time

Write a `terrastep.toml` naming `scan_dirs`, run `migrate propose`/`apply` on what's already
there, then `terrastep install-hooks`. See `references/verbs.md` for every verb and flag.
"""


def render_skill_md() -> str:
    frontmatter = (
        "---\n"
        "name: terrastep\n"
        "description: Use when writing, reviewing, or checking a terrastep design/plan/proposal "
        "document, or a task mentions terrastep, scan_dirs, or the Blockers/Questions/"
        "Recommendations/Sequencing document shape. Not for markdown outside a repository's "
        "terrastep scan_dirs.\n"
        f"terrastep_version: {__version__}\n"
        "---\n"
    )
    body = (
        f"\n{GENERATED_NOTE} (terrastep {__version__})\n\n"
        "# terrastep\n\n"
        "terrastep checks planning documents against a frontmatter-and-body format. Full spec: "
        "`references/format.md`. Full verb/config reference: `references/verbs.md`.\n\n"
        + SKILL_PROCEDURE
    )
    return frontmatter + body


def render_reference_format() -> str:
    parts = [
        _header("terrastep format reference"),
        "### States, types, and closed reasons\n",
        _states_and_types_table(),
        "\n### Role headings\n",
        _role_alias_table(),
        "\n### Failure codes\n",
        _failure_code_table(),
    ]
    return "\n".join(parts) + "\n"


def render_reference_verbs() -> str:
    parts = [
        _header("terrastep verb and config reference"),
        "### Verbs\n",
        _verb_table(),
        "\n### `terrastep.toml`\n",
        _config_table(),
    ]
    return "\n".join(parts) + "\n"


def render_all() -> dict[str, str]:
    """{relative path: content} for every generated file, terrastep_101.md and the skill."""
    return {
        "journal/terrastep_101.md": render_terrastep_101(),
        "skill/SKILL.md": render_skill_md(),
        "skill/references/format.md": render_reference_format(),
        "skill/references/verbs.md": render_reference_verbs(),
    }
